# Override values for HyperShift 
global:
  useExternalSecrets: true
  s3:
    createBucket: true
    region: us-west-1
    bucketName: jr-hcp-demo
    additionalTags:
      owner: jrickard
  
  buildconfig:
    git:
      uri: https://github.com/day0hero/hypershift
      ref: main
