apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '15'
  name: ack-system-operator-group
  namespace: ack-system
spec:
  upgradeStrategy: Default
